// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrXT_rtNgqx0BSGvve8MT-2e7l0lI6bPE',
    appId: '1:800586548586:web:cea7a5547b36139dc9d113',
    messagingSenderId: '800586548586',
    projectId: 'frontend-3adf1',
    authDomain: 'frontend-3adf1.firebaseapp.com',
    storageBucket: 'frontend-3adf1.appspot.com',
    measurementId: 'G-Z2MRDMW7JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjEUDyhmmiv0UNEknrjzbv68I8IlamOQ',
    appId: '1:800586548586:android:4bcb56a3c7570a92c9d113',
    messagingSenderId: '800586548586',
    projectId: 'frontend-3adf1',
    storageBucket: 'frontend-3adf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6LxegYk6ZfcVR73fr6nnDH9W2eI8vmG8',
    appId: '1:800586548586:ios:3ce6dab52cb8ed3fc9d113',
    messagingSenderId: '800586548586',
    projectId: 'frontend-3adf1',
    storageBucket: 'frontend-3adf1.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6LxegYk6ZfcVR73fr6nnDH9W2eI8vmG8',
    appId: '1:800586548586:ios:baaad13b12cececbc9d113',
    messagingSenderId: '800586548586',
    projectId: 'frontend-3adf1',
    storageBucket: 'frontend-3adf1.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
